syndo:
  components:
    - name: base
      from: registry.access.redhat.com/ubi8/openjdk-11:1.3
      to: base
      path: base
    - name: application
      from: base
      to: application
      path: application
    - name: docker
      dockerfile: subdir/Dockerfile
      path: docker
  aliases:
    - name: slim
      includes:
        - base
        - app