name: Build Syndo Release Artifacts
on:
  push:
    branches:
      - release-*
    tags:
      - release-*
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Capture pom version
        run: |
          echo "POM_VER=${POM_VER}" >> $GITHUB_ENV

      - name: Capture branch info
        if: contains(github.ref, 'refs/heads/')
        run: |
          echo "PRERELEASE=true" >> $GITHUB_ENV

      - name: Capture branch info
        if: "!contains(github.ref, 'refs/heads/')"
        run: |
          echo "PRERELEASE=false" >> $GITHUB_ENV

      - name: Capture outputs
        id: metadata
        run: |
          echo "::set-output name=pom-ver::${{ env.POM_VER }}"
          echo "::set-output name=decide::${{ env.PRERELEASE }}"

    outputs:
      pom-ver: ${{ steps.metadata.outputs.pom-ver }}
      prerelease: ${{ steps.metadata.outputs.prerelease }}

  prepare:
    needs: [metadata, verify]
    runs-on: ubuntu-latest
    steps:
      - name: Delete release/tag if it exists
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create target release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          prerelease: ${{ needs.metadata.outputs.prerelease }}

  build_jars:
    # dependency on verification
    needs: [metadata, prepare]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests package

      - name: Upload java binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/syndo-${{ needs.metadata.outputs.pom-ver }}.jar
          asset_name: syndo-${{ needs.metadata.outputs.pom-ver }}.jar
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ needs.metadata.outputs.prerelease }}

      - name: Upload java executable binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/syndo-${{ needs.metadata.outputs.pom-ver }}-shaded.jar
          asset_name: syndo-${{ needs.metadata.outputs.pom-ver }}-executable.jar
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ needs.metadata.outputs.prerelease }}

  build_native:
    # dependency on verification
    needs: [metadata, prepare]

    # run this job on the current template instantiation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gu-binary: gu
            native-asset-suffix: linux-amd64
          - os: windows-2016
            gu-binary: gu.cmd
            native-asset-suffix: windows-amd64
    steps:
      # install GraalVM for native build
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      - name: Add msbuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Add toolkit to path
        if: contains(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install native-image component
        run: |
          ${{ matrix.gu-binary }} install native-image

      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests -Pnative package

      - name: Upload native binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/syndo
          asset_name: syndo-${{ needs.metadata.outputs.pom-ver }}-${{ matrix.native-asset-suffix }}
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: ${{ needs.metadata.outputs.prerelease }}