name: Build Syndo Release Artifacts
on:
  push:
    branches:
      - release-*
    tags:
      - release-*
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  build_jar:
    # dependency on verification
    needs: verify

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests package

      - name: Capture pom version
        run: |
          echo "POM_VER=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Upload java binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/syndo-${{ env.POM_VER }}-0.2.0.jar
          asset_name: syndo-${{ env.POM_VER }}-0.2.0.jar
          tag: ${{ github.ref }}-unstable
          overwrite: true

      - name: Upload java executable binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/syndo-${{ env.POM_VER }}-0.2.0-shaded.jar
          asset_name: syndo-${{ env.POM_VER }}-0.2.0-executable.jar
          tag: ${{ github.ref }}-unstable
          overwrite: true

  build_native:
    # dependency on verification
    needs: verify

    # run this job on the current template instantiation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            gu-binary: gu
            native-asset: syndo-linux-amd64
          - os: windows-2016
            gu-binary: gu.cmd
            native-asset: syndo-windows-amd64
    steps:
      # install GraalVM for native build
      - uses: DeLaGuardo/setup-graalvm@4.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      - name: Add msbuild to PATH
        if: contains(matrix.os, 'windows')
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Add toolkit to path
        if: contains(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install native-image component
        run: |
          ${{ matrix.gu-binary }} install native-image

      - uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots -DskipTests -Pnative package

      - name: Upload native binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/syndo
          asset_name: ${{ matrix.native-asset }}
          tag: ${{ github.ref }}-unstable
          overwrite: true